config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:new, :create]

  get '/dish_counts', to: 'orders#dish_counts'

  root "orders#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :recipes, dependent: :destroy
  has_many :ingredients, through: :recipes
  has_and_belongs_to_many :orders

  scope :exclude_ingredients, -> (ingredient_ids) {
    where.not(id: joins(:ingredients)
    .where(ingredients: { id: ingredient_ids })
    .select(:id)) }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :recipes, dependent: :destroy
  has_many :dishes, through: :recipes
end

app/models/order.rb
class Order < ApplicationRecord
  has_and_belongs_to_many :dishes

  def self.dish_counts
    dishes = joins(:dishes).group(:name).count
    dishes.map { |name, count| { name: name, count: count } }.sort_by { |dish| -dish[:count] }
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :dish
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :load_ingredients, only: %i[new]
  
  def dish_counts
    @dish_counts = Order.dish_counts
    render json: @dish_counts
  end
  
  def create
    @order = Order.new
    @order.dishes = Dish.exclude_ingredients(params[:ingredient_ids])
    if @order.dishes.empty?
      flash[:notice] = "No dishes available with such set of ingredients"
    else
      @order.save
      flash[:notice] = "Your order has been created"
    end
    redirect_to new_order_path
  end

  def new
    @order = Order.new
  end

  private

  def load_ingredients
    @ingredients = Ingredient.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/orders/new.html.slim
h1 = 'New Order'

.ingredients
  = form_with url: orders_path(@order) do |form|
    = form.collection_check_boxes :ingredient_ids, @ingredients, :id, :name, include_hidden: false do |i|
      p
        = i.check_box
        = i.label
    = form.submit 'Send Order'  

app/views/shared/_flashes.html.erb
<% if notice %>
  <div>
    <%= notice %>
  </div>
<% end %>